### PR TITLE
remove redundant jvm flags

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
The good news is that your machine can compile and run the tests. The bad news is there's some consistent issue with compiling sources with scala 2.11. It's still doing a jvm abort. Doesn't happen on my drone machine.

**Comment by chipsenkbeil** [comment]
@fommil, any thoughts on this problem? Happens consistently for Scala 2.11 when compiling on your machine. So far, I have to use my ci that runs purely on my machine to avoid the problem. Have not encountered this fatal error on any of my laptops, desktop computer, or server.

https://ci.fommil.com/ensime/scala-debugger/8/2

**Comment by fommil** [comment]
Hmm

**Comment by chipsenkbeil** [comment]
Had to cancel appveyor build (stuck). LGTM otherwise.

**Pull request merged**
